const PDFDocument = require('pdfkit');
const fs = require('fs');

const out = process.argv[2] || 'tmp/valid-test.pdf';
fs.mkdirSync(require('path').dirname(out), { recursive: true });

const doc = new PDFDocument();
const stream = fs.createWriteStream(out);
doc.pipe(stream);

doc.fontSize(20).text('AI Demo - Test PDF', { align: 'center' });
doc.moveDown();
doc.fontSize(12).text('This is a valid PDF generated by pdfkit for testing pdf-parse extraction.', { align: 'left' });
doc.moveDown();
doc.text('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.');
doc.addPage();
doc.fontSize(14).text('Second page content: more text to ensure multiple pages are parsed correctly.');

doc.end();

stream.on('finish', () => {
  console.log('PDF generated at', out);
});
